### ISSUE TITLE
Extension doesn't work in visual studio code insiders

### ISSUE THREAD

**Issue by xgrommx** [alanz/vscode-hie-server#147]
Hello @alanz. I have some problem with visual studio code insiders. On usual version it works correctly but on insiders version not.

**Comment by theGhostJW** [comment]
Hi
It looks like that problem is now in the main release.
Went from everything working perfectly -> nothing working with update to this version of VSCode

Version: 1.33.0 (system setup)
Commit: 0dd516dd412d42323fc3464531b1c715d51c4c1a
Date: 2019-04-04T15:14:28.026Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

@xgrommx  might be an idea to update the title to "Extension stopped working V 1.33.0" given your insiders edition has now been released to the great unwashed.

**Comment by theGhostJW** [comment]
Downgrading VS Code:
  * File > Preferences > Settings <User Tab><Search For: Update>
  * I disabled all the following settings, some of these changes might not be required but <Update Mode> definitely is:
    * Update: Enable Windows Background Updates  - UNCHECKED
    * Update: Mode - NONE
    * Extensions: AutoCheck Updates: UNCHECKED
  * Download and install previous version from: https://code.visualstudio.com/updates/v1_32

**Comment by alanz** [comment]
I just hit this too.  I guess I need to skill up on how vscode works.

**Comment by david9991** [comment]
Same here...

**Comment by AlexeyRaga** [comment]
This should be fixed now with https://github.com/JustusAdam/language-haskell/issues/84.
I don't use insiders versions, @xgrommx please verify.

**Comment by xgrommx** [comment]
@AlexeyRaga yes, now it works as expected.
