### ISSUE TITLE
Add some indication that hie is busy

### ISSUE THREAD

**Issue by flip111** [alanz/vscode-hie-server#203]
When opening a project it can happen that `hie` still takes a long time to compile things. At the moment there is no visual indication (as far as i know) that vscode-hie-server is waiting for this to complete. So you spend time with "it doesn't work" .. and then later it works. Maybe a spinner somewhere or a pop-up would do.

**Comment by fendor** [comment]
That mainly happens with `hie-wrapper` and using the implicit cradle. 
The reason is that `hie-wrapper` needs to know the ghc version to know which hie version should be used in the project. However, to know the project ghc version, e.g. in stack, we need to configure the project, which builds all the dependencies of the project. Only then we can start the correct hie version.
The problem now is, that hie-wrapper is not a lsp-server, it is barely more than a script, it can not report stuff back to vscode easily.
If you start the correct hie version directly, you will notice that progress notifications are already implemented.

**Comment by flip111** [comment]
If there is a map available from stack resolver to ghc version all that is needed is to parse stack.yaml this will speed up things a lot.

Looks like the situation with hie-wrapper at the moment is not ideal. Maybe it can have more LSP-server like features.

**Comment by fendor** [comment]
Yes, that is true. But not that trivial to implement.

Easier said than done.

**Comment by flip111** [comment]
Maybe close this issue if there is a meta issue for possible improvements to hie-wrapper

**Comment by fendor** [comment]
Closed in favour of https://github.com/haskell/haskell-ide-engine/issues/1640
