### ISSUE TITLE
"hie executable missing" upon start

### ISSUE THREAD

**Issue by soylens** [alanz/vscode-hie-server#34]
I have installed it as instructed and it is in the PATH
Force Start works

**Comment by soylens** [comment]
It seems that the function isHieInstalled does not work properly
Apparantly because of there is no "which" command under any shell with Windoes

**Comment by Tehnix** [comment]
Hmm, I thought Windows would use https://github.com/alanz/vscode-hie-server/blob/master/hie-vscode.bat to run HIE (i.e. no `which` used) 🤔

**Comment by soylens** [comment]
hmm, i think that only works with cmd, but not powershell
(i ran `where hie` in Posh and it output nothing)
(I set the default shell to cmd and it didnt help either)
I think it would help to let the user specifie the hie executable, although it might be a little inconvenient.
i currently have no idea of other solutions

**Comment by soylens** [comment]
No what the hell

**Comment by soylens** [comment]
btw does this handle the applying hlint suggestion part? it doesnt funtion properly with me

**Comment by nponeccop** [comment]
`which` is not present on Windows, and even on Linux/MacOS something less fragile should be used.

Interestingly there are already such modules on `npm`, e.g. `command-exists`, and it uses `command` (which is shell builtin so it's present in more cases than `which`) and `where` on Windows.

Maybe we should depend on `command-exists` or similar for cross-platform checks instead of making our own.

**Comment by hanjoosten** [comment]
Indeed. I copied `where.exe` to my utils directory, which is in the path.
